### PR TITLE
changes after comments from Max

### PR DESCRIPTION
**Pull request by gyrusdentatus**
line 23 back to it's former state and got rid of the 48-60, only kept one sentence about `source ~/.cargo/env` at line 55

### CODE REVIEW

**Comment by gyrusdentatus** [comment]
@mfahampshire should I close the previous PR #84 , and open a PR against develop if you agree with the changes I've made? 

let me know, pls. 
Cheers!

**Comment by mfahampshire** [comment]
Yep please close the other PR, and remove line 55 as info to that effect is already logged at the end of the rust installer script iirc. Thanks

**Comment by gyrusdentatus** [comment]
Ok I have figured out why I wanted to add this option:
A
dding `source $HOME/.cargo/env` to the `.bash_profile` is only needed on MacOS (I was constantly having to type manually `source ~/.cargo/env` because it was not added to the `.bash_profile` (not using `zsh` on my system but it was the same thing with `zsh` anyway...)

On Linux it works just fine with only using `source` once. Good point!

**Comment by gyrusdentatus** [comment]
You can close this after seeing #87

**Pull request closed without merging**
