### PR TITLE
add: which nr to download

### PR DESCRIPTION
**Pull request by sven-hash**

### CODE REVIEW

**Comment by mfahampshire** [comment]
I'll change this to adding a note / link to the NR docs page itself

**Comment by mfahampshire** [comment]
Just an FYI - when adding links to the most recent  release version on github, remember to use the `{{platform_release_version}}` variable in the URL - it means that it'll always check out to the latest release version :)

**Comment by mfahampshire** [comment]
> Just an FYI - when adding links to the most recent release version on github, remember to use the `{{platform_release_version}}` variable in the URL - it means that it'll always check out to the latest release version :)

This is defined in `book.toml` in the `[preprocessor.variables.variables]` section

**Comment by sven-hash** [comment]
I saw this but you need to use a specific network requester because the new ones embed the nym-client directly and it's not possible to use them with zk-nym yet

**Comment by sven-hash** [comment]
Feel free to adapt my changes if you have any informations

**Comment by mfahampshire** [comment]
Isn't the link you had included just the generic network requester binary?

**Comment by sven-hash** [comment]
> Isn't the link you had included just the generic network requester binary?

It's the last version I found without the nym-client in it

**Comment by mfahampshire** [comment]
Ahaa that makes sense.

**Pull request merged**
