### PR TITLE
Initial Version of CN Translation

### PR DESCRIPTION
**Pull request by myz1237**
Hi Max
If you are in hurry to publish the mainnet doc, you could use this version. Also, I modify some links of stable version and leave comments. I will review the link and contents in a few days and pr again.

Yizhuo

### CODE REVIEW

**Comment by mfahampshire** [comment]
Hey - these look great, but I think we can wait a few days, no massive rush. 

Just to bring this branch to your attention: I did version + build information bumps in this branch: https://github.com/nymtech/docs/tree/v1_0_1-version-bump

**Comment by mfahampshire** [comment]
@myz1237 any updates on this? Let me know if i can assist at all

**Comment by myz1237** [comment]
@mfahampshire Thanks for your help, max. I notice that feature/v1 is out of date. So which brach should I use now? I could update translation based on current contents

**Comment by mfahampshire** [comment]
> @mfahampshire Thanks for your help, max. I notice that feature/v1 is out of date. So which brach should I use now? I could update translation based on current contents

For the moment you can work from `master` branch, this is up to date

**Comment by mfahampshire** [comment]
Closing this PR as you finished this work in another PR. Thanks :)

**Pull request closed without merging**
