### PR TITLE
Update zh Translation and correct tiny sentence errors

### PR DESCRIPTION
**Pull request by myz1237**
Hi Max,

I am Yizhuo who maintains zh translations. The translated contents have been tested with `npm run start -- --locale zh` and the web works well. I think it's ok to directly push the contents to nym doc pages. Btw, I correct some tiny, tiny sentence errors. Actually, those cannot be called errors, just my rigidness.

### CODE REVIEW

**Comment by mfahampshire** [comment]
Hi @myz1237 - this all looks good to me aside from one small thing: the translation of 'develop with Nym' seems to be different between the stable and next versions - could you check into this please? 

Thanks again.

**Comment by myz1237** [comment]
I will recheck the whole doc to make sure everything is fine.

**Comment by myz1237** [comment]
@mfahampshire 'ExecStart=/home/jetpanther/nym/target/release/nym-mixnode run --id your-id. Basically, you want the full /path/to/nym-mixnode run --id whatever-your-node-id-is', I don't get it. What 'Basically, you want the full ' means? You want to clarify absolute and relative path?

**Review by mfahampshire — APPROVED** [review]
this all looks good to me!

**Comment by mfahampshire** [comment]
> @mfahampshire 'ExecStart=/home/jetpanther/nym/target/release/nym-mixnode run --id your-id. Basically, you want the full /path/to/nym-mixnode run --id whatever-your-node-id-is', I don't get it. What 'Basically, you want the full ' means? You want to clarify absolute and relative path?

Yes you want the absolute path in there

**Pull request merged**
